In [38]:
import json
import os
from typing import Any

import polars as pl

In [39]:
# PROCESS RIKISHI

base_dir_rikishi = "raw_data/rikishi"

all_item_keys_rikishi = set(
    [
        "id",
        "sumodbId",
        "nskId",
        "shikonaEn",
        "heya",
        "birthDate",
        "shusshin",
        "height",
        "weight",
        "debut",
        "intai",
        "shikonaJp",
        "currentRank",
        "updatedAt",
        "createdAt",
    ]
)

all_data_rikishi: list[dict[str, Any]] = []
file_names_rikishi = os.listdir(base_dir_rikishi)
file_names_rikishi.sort()
for fn in file_names_rikishi:
    with open(os.path.join(base_dir_rikishi, fn)) as f:
        data = json.load(f)
        if "records" in data:
            items = data["records"]
            for item in items:
                keys = set(item.keys())
                if keys != all_item_keys_rikishi:
                    print(f"{fn} does not have consistent keys")
                    missing_keys = all_item_keys_rikishi.difference(keys)
                    if missing_keys:
                        print(f"- missing: {missing_keys}")
                    extra_keys = keys.difference(all_item_keys_rikishi)
                    if extra_keys:
                        print(f"- extra: {extra_keys}")
            all_data_rikishi += items
        else:
            print(f"{fn} does not contain 'records' key.")

schema_rikishi: dict[str, pl.DataType] = {
    "id": pl.Int64,
    "shikonaEn": pl.String,
    "birthDate": pl.String,
    "shusshin": pl.String,
    "debut": pl.String,
    "intai": pl.String,
}  # type: ignore

df_rikishi = pl.from_dicts(all_data_rikishi, schema=schema_rikishi)

df_rikishi = df_rikishi.with_columns(
    pl.col("birthDate").replace("0001-01-01T00:00:00Z", None),
    pl.col("intai").replace("0001-01-01T00:00:00Z", None),
)
df_rikishi = df_rikishi.with_columns(
    pl.col("birthDate").str.to_date("%Y-%m-%dT%H:%M:%SZ"),
    pl.col("intai").str.to_date("%Y-%m-%dT%H:%M:%SZ"),
)

df_rikishi

0_1000.json does not have consistent keys
- missing: {'createdAt', 'updatedAt', 'shikonaJp', 'currentRank'}
0_1000.json does not have consistent keys
- missing: {'createdAt', 'intai'}
0_1000.json does not have consistent keys
- missing: {'createdAt', 'intai'}
0_1000.json does not have consistent keys
- missing: {'createdAt', 'intai'}
0_1000.json does not have consistent keys
- missing: {'createdAt', 'intai'}
0_1000.json does not have consistent keys
- missing: {'createdAt', 'intai'}
0_1000.json does not have consistent keys
- missing: {'createdAt', 'intai'}
0_1000.json does not have consistent keys
- missing: {'createdAt', 'intai'}
0_1000.json does not have consistent keys
- missing: {'createdAt', 'intai'}
0_1000.json does not have consistent keys
- missing: {'createdAt', 'updatedAt', 'shikonaJp', 'currentRank'}
0_1000.json does not have consistent keys
- missing: {'createdAt', 'intai'}
0_1000.json does not have consistent keys
- missing: {'createdAt', 'intai'}
0_1000.json does not have consistent keys
- missing: {'createdAt', 'intai'}
0_1000.json does not have consistent keys
- missing: {'createdAt', 'intai'}
0_1000.json does not have consistent keys
- missing: {'createdAt', 'intai'}
0_1000.json does not have consistent keys
- missing: {'createdAt', 'intai'}
0_1000.json does not have consistent keys
- missing: {'createdAt', 'intai'}
0_1000.json does not have consistent keys
- missing: {'createdAt', 'updatedAt', 'shikonaJp', 'currentRank'}
0_1000.json does not have consistent keys
- missing: {'createdAt', 'intai'}
0_1000.json does not have consistent keys
- missing: {'createdAt', 'intai'}
0_1000.json does not have consistent keys
- missing: {'createdAt', 'intai'}
0_1000.json does not have consistent keys
- missing: {'createdAt', 'intai'}
0_1000.json does not have consistent keys
- missing: {'createdAt', 'updatedAt', 'shikonaJp', 'currentRank'}
0_1000.json does not have consistent keys
- missing: {'createdAt', 'intai'}
0_1000.json does not have consistent keys
- missing: {'createdAt', 'intai'}
0_1000.json does not have consistent keys
- missing: {'createdAt', 'intai'}
0_1000.json does not have consistent keys
- missing: {'createdAt', 'intai'}
0_1000.json does not have consistent keys
- missing: {'createdAt', 'intai'}
0_1000.json does not have consistent keys
- missing: {'createdAt', 'intai'}
0_1000.json does not have consistent keys
- missing: {'createdAt', 'updatedAt', 'shikonaJp', 'currentRank'}
0_1000.json does not have consistent keys
- missing: {'createdAt', 'intai'}
0_1000.json does not have consistent keys
- missing: {'createdAt', 'intai'}
0_1000.json does not have consistent keys
- missing: {'createdAt', 'intai'}
0_1000.json does not have consistent keys
- missing: {'createdAt', 'intai'}
0_1000.json does not have consistent keys
- missing: {'createdAt', 'intai'}
0_1000.json does not have consistent keys
- missing: {'createdAt', 'updatedAt', 'shikonaJp', 'currentRank'}
0_1000.json does not have consistent keys
- missing: {'createdAt', 'intai'}
0_1000.json does not have consistent keys
- missing: {'createdAt', 'intai'}
0_1000.json does not have consistent keys
- missing: {'createdAt', 'intai'}
0_1000.json does not have consistent keys
- missing: {'createdAt', 'intai'}
0_1000.json does not have consistent keys
- missing: {'createdAt', 'intai'}
0_1000.json does not have consistent keys
- missing: {'createdAt', 'intai'}
0_1000.json does not have consistent keys
- missing: {'createdAt', 'updatedAt', 'shikonaJp', 'currentRank'}
0_1000.json does not have consistent keys
- missing: {'createdAt', 'intai'}
0_1000.json does not have consistent keys
- missing: {'createdAt', 'currentRank'}
0_1000.json does not have consistent keys
- missing: {'createdAt', 'updatedAt', 'shikonaJp', 'currentRank'}
0_1000.json does not have consistent keys
- missing: {'createdAt', 'updatedAt', 'shikonaJp', 'currentRank'}
0_1000.json does not have consistent keys
- missing: {'createdAt', 'intai'}
0_1000.json does not have consistent keys
- missing: {'createdAt', 'intai'}
0_1000.json does not have consistent keys
- missing: {'createdAt', 'intai'}
0_1000.json does not have consistent keys
- missing: {'createdAt', 'updatedAt', 'shikonaJp', 'currentRank'}
0_1000.json does not have consistent keys
- missing: {'createdAt', 'intai'}
0_1000.json does not have consistent keys
- missing: {'createdAt', 'updatedAt', 'shikonaJp', 'currentRank'}
0_1000.json does not have consistent keys
- missing: {'createdAt', 'intai'}
0_1000.json does not have consistent keys
- missing: {'createdAt', 'intai'}
0_1000.json does not have consistent keys
- missing: {'createdAt', 'intai'}
0_1000.json does not have consistent keys
- missing: {'createdAt', 'intai'}
0_1000.json does not have consistent keys
- missing: {'createdAt', 'intai'}
0_1000.json does not have consistent keys
- missing: {'createdAt', 'intai'}
0_1000.json does not have consistent keys
- missing: {'createdAt', 'intai'}
0_1000.json does not have consistent keys
- missing: {'createdAt', 'intai'}
0_1000.json does not have consistent keys
- missing: {'createdAt', 'intai'}
0_1000.json does not have consistent keys
- missing: {'createdAt', 'intai'}
0_1000.json does not have consistent keys
- missing: {'createdAt', 'intai'}
0_1000.json does not have consistent keys
- missing: {'createdAt', 'intai'}
0_1000.json does not have consistent keys
- missing: {'createdAt', 'intai'}
0_1000.json does not have consistent keys
- missing: {'createdAt', 'updatedAt', 'shikonaJp', 'currentRank'}
0_1000.json does not have consistent keys
- missing: {'createdAt', 'intai'}
0_1000.json does not have consistent keys
- missing: {'createdAt', 'intai'}
0_1000.json does not have consistent keys
- missing: {'createdAt', 'intai'}
0_1000.json does not have consistent keys
- missing: {'createdAt', 'intai'}
0_1000.json does not have consistent keys
- missing: {'createdAt', 'intai'}
0_1000.json does not have consistent keys
- missing: {'createdAt', 'intai'}
0_1000.json does not have consistent keys
- missing: {'createdAt', 'intai'}
0_1000.json does not have consistent keys
- missing: {'createdAt', 'intai'}
0_1000.json does not have consistent keys
- missing: {'createdAt', 'intai'}
0_1000.json does not have consistent keys
- missing: {'createdAt', 'intai'}
0_1000.json does not have consistent keys
- missing: {'createdAt', 'intai'}
0_1000.json does not have consistent keys
- missing: {'createdAt', 'updatedAt', 'shikonaJp', 'currentRank'}
0_1000.json does not have consistent keys
- missing: {'createdAt', 'intai'}
0_1000.json does not have consistent keys
- missing: {'createdAt', 'intai'}
0_1000.json does not have consistent keys
- missing: {'createdAt', 'intai'}
0_1000.json does not have consistent keys
- missing: {'createdAt', 'intai'}
0_1000.json does not have consistent keys
- missing: {'createdAt', 'intai'}
0_1000.json does not have consistent keys
- missing: {'createdAt', 'intai'}
0_1000.json does not have consistent keys
- missing: {'createdAt', 'intai'}
0_1000.json does not have consistent keys
- missing: {'createdAt', 'intai'}
0_1000.json does not have consistent keys
- missing: {'createdAt', 'intai'}
0_1000.json does not have consistent keys
- missing: {'createdAt', 'intai'}
0_1000.json does not have consistent keys
- missing: {'createdAt', 'intai'}
0_1000.json does not have consistent keys
- missing: {'createdAt', 'intai'}
0_1000.json does not have consistent keys
- missing: {'createdAt', 'updatedAt', 'shikonaJp', 'currentRank'}
0_1000.json does not have consistent keys
- missing: {'createdAt', 'intai'}
0_1000.json does not have consistent keys
- missing: {'createdAt', 'intai'}
0_1000.json does not have consistent keys
- missing: {'createdAt', 'intai'}
0_1000.json does not have consistent keys
- missing: {'createdAt', 'intai'}
0_1000.json does not have consistent keys
- missing: {'createdAt', 'intai'}
0_1000.json does not have consistent keys
- missing: {'createdAt', 'intai'}
0_1000.json does not have consistent keys
- missing: {'createdAt', 'updatedAt', 'shikonaJp', 'currentRank'}
0_1000.json does not have consistent keys
- missing: {'createdAt', 'intai'}
0_1000.json does not have consistent keys
- missing: {'createdAt', 'intai'}
0_1000.json does not have consistent keys
- missing: {'createdAt', 'intai'}
0_1000.json does not have consistent keys
- missing: {'createdAt', 'updatedAt', 'shikonaJp', 'currentRank'}
0_1000.json does not have consistent keys
- missing: {'createdAt', 'updatedAt', 'shikonaJp', 'currentRank'}
0_1000.json does not have consistent keys
- missing: {'createdAt', 'updatedAt', 'shikonaJp', 'currentRank'}
0_1000.json does not have consistent keys
- missing: {'createdAt', 'intai'}
0_1000.json does not have consistent keys
- missing: {'createdAt', 'intai'}
0_1000.json does not have consistent keys
- missing: {'createdAt', 'intai'}
0_1000.json does not have consistent keys
- missing: {'createdAt', 'updatedAt', 'shikonaJp', 'currentRank'}
0_1000.json does not have consistent keys
- missing: {'createdAt', 'intai'}
0_1000.json does not have consistent keys
- missing: {'createdAt', 'intai'}
0_1000.json does not have consistent keys
- missing: {'createdAt', 'intai'}
0_1000.json does not have consistent keys
- missing: {'createdAt', 'intai'}
0_1000.json does not have consistent keys
- missing: {'createdAt', 'intai'}
0_1000.json does not have consistent keys
- missing: {'createdAt', 'updatedAt', 'shikonaJp', 'currentRank'}
0_1000.json does not have consistent keys
- missing: {'createdAt', 'intai'}
0_1000.json does not have consistent keys
- missing: {'createdAt', 'intai'}
0_1000.json does not have consistent keys
- missing: {'createdAt', 'intai'}
0_1000.json does not have consistent keys
- missing: {'createdAt', 'intai'}
0_1000.json does not have consistent keys
- missing: {'createdAt', 'intai'}
0_1000.json does not have consistent keys
- missing: {'createdAt', 'intai'}
0_1000.json does not have consistent keys
- missing: {'createdAt', 'intai'}
0_1000.json does not have consistent keys
- missing: {'createdAt', 'intai'}
0_1000.json does not have consistent keys
- missing: {'createdAt', 'intai'}
0_1000.json does not have consistent keys
- missing: {'createdAt', 'intai'}
0_1000.json does not have consistent keys
- missing: {'createdAt', 'intai'}
0_1000.json does not have consistent keys
- missing: {'createdAt', 'updatedAt', 'shikonaJp', 'currentRank'}
0_1000.json does not have consistent keys
- missing: {'createdAt', 'intai'}
0_1000.json does not have consistent keys
- missing: {'createdAt', 'intai'}
0_1000.json does not have consistent keys
- missing: {'createdAt', 'intai'}
0_1000.json does not have consistent keys
- missing: {'createdAt', 'intai'}
0_1000.json does not have consistent keys
- missing: {'createdAt', 'intai'}
0_1000.json does not have consistent keys
- missing: {'createdAt', 'updatedAt', 'shikonaJp', 'currentRank'}
0_1000.json does not have consistent keys
- missing: {'createdAt', 'intai'}
0_1000.json does not have consistent keys
- missing: {'createdAt', 'intai'}
0_1000.json does not have consistent keys
- missing: {'createdAt', 'intai'}
0_1000.json does not have consistent keys
- missing: {'createdAt', 'intai'}
0_1000.json does not have consistent keys
- missing: {'createdAt', 'updatedAt', 'shikonaJp', 'currentRank'}
0_1000.json does not have consistent keys
- missing: {'createdAt', 'updatedAt', 'shikonaJp', 'currentRank'}
0_1000.json does not have consistent keys
- missing: {'createdAt', 'intai'}
0_1000.json does not have consistent keys
- missing: {'createdAt', 'intai'}
0_1000.json does not have consistent keys
- missing: {'createdAt', 'intai'}
0_1000.json does not have consistent keys
- missing: {'createdAt', 'intai'}
0_1000.json does not have consistent keys
- missing: {'createdAt', 'intai'}
0_1000.json does not have consistent keys
- missing: {'createdAt', 'intai'}
0_1000.json does not have consistent keys
- missing: {'createdAt', 'updatedAt', 'shikonaJp', 'currentRank'}
0_1000.json does not have consistent keys
- missing: {'createdAt', 'updatedAt', 'shikonaJp', 'currentRank'}
0_1000.json does not have consistent keys
- missing: {'createdAt', 'updatedAt', 'shikonaJp', 'currentRank'}
0_1000.json does not have consistent keys
- missing: {'createdAt', 'intai'}
0_1000.json does not have consistent keys
- missing: {'createdAt', 'intai'}
0_1000.json does not have consistent keys
- missing: {'createdAt', 'intai'}
0_1000.json does not have consistent keys
- missing: {'createdAt', 'intai'}
0_1000.json does not have consistent keys
- missing: {'createdAt', 'intai'}
0_1000.json does not have consistent keys
- missing: {'createdAt', 'intai'}
0_1000.json does not have consistent keys
- missing: {'createdAt', 'intai'}
0_1000.json does not have consistent keys
- missing: {'createdAt', 'intai'}
0_1000.json does not have consistent keys
- missing: {'createdAt', 'updatedAt', 'shikonaJp', 'currentRank'}
0_1000.json does not have consistent keys
- missing: {'createdAt', 'updatedAt', 'shikonaJp', 'currentRank'}
0_1000.json does not have consistent keys
- missing: {'createdAt', 'intai'}
0_1000.json does not have consistent keys
- missing: {'createdAt', 'intai'}
0_1000.json does not have consistent keys
- missing: {'createdAt', 'intai'}
0_1000.json does not have consistent keys
- missing: {'createdAt', 'intai'}
0_1000.json does not have consistent keys
- missing: {'createdAt', 'intai'}
0_1000.json does not have consistent keys
- missing: {'createdAt', 'intai'}
0_1000.json does not have consistent keys
- missing: {'createdAt', 'intai'}
0_1000.json does not have consistent keys
- missing: {'createdAt', 'intai'}
0_1000.json does not have consistent keys
- missing: {'createdAt', 'intai'}
0_1000.json does not have consistent keys
- missing: {'createdAt', 'intai'}
0_1000.json does not have consistent keys
- missing: {'createdAt', 'intai'}
0_1000.json does not have consistent keys
- missing: {'createdAt', 'intai'}
0_1000.json does not have consistent keys
- missing: {'createdAt', 'intai'}
0_1000.json does not have consistent keys
- missing: {'createdAt', 'intai'}
0_1000.json does not have consistent keys
- missing: {'createdAt', 'intai'}
0_1000.json does not have consistent keys
- missing: {'createdAt', 'updatedAt', 'shikonaJp', 'currentRank'}
0_1000.json does not have consistent keys
- missing: {'createdAt', 'intai'}
0_1000.json does not have consistent keys
- missing: {'createdAt', 'intai'}
0_1000.json does not have consistent keys
- missing: {'createdAt', 'intai'}
0_1000.json does not have consistent keys
- missing: {'createdAt', 'intai'}
0_1000.json does not have consistent keys
- missing: {'createdAt', 'intai'}
0_1000.json does not have consistent keys
- missing: {'createdAt', 'intai'}
0_1000.json does not have consistent keys
- missing: {'createdAt', 'intai'}
0_1000.json does not have consistent keys
- missing: {'createdAt', 'intai'}
0_1000.json does not have consistent keys
- missing: {'createdAt', 'intai'}
0_1000.json does not have consistent keys
- missing: {'createdAt', 'intai'}
0_1000.json does not have consistent keys
- missing: {'createdAt', 'intai'}
0_1000.json does not have consistent keys
- missing: {'createdAt', 'intai'}
0_1000.json does not have consistent keys
- missing: {'createdAt', 'intai'}
0_1000.json does not have consistent keys
- missing: {'createdAt', 'intai'}
0_1000.json does not have consistent keys
- missing: {'createdAt', 'updatedAt', 'shikonaJp', 'currentRank'}
0_1000.json does not have consistent keys
- missing: {'createdAt', 'intai'}
0_1000.json does not have consistent keys
- missing: {'createdAt', 'updatedAt', 'shikonaJp', 'currentRank'}
0_1000.json does not have consistent keys
- missing: {'createdAt', 'intai'}
0_1000.json does not have consistent keys
- missing: {'createdAt', 'updatedAt', 'shikonaJp', 'currentRank'}
0_1000.json does not have consistent keys
- missing: {'createdAt', 'intai'}
0_1000.json does not have consistent keys
- missing: {'createdAt', 'intai'}
0_1000.json does not have consistent keys
- missing: {'createdAt', 'updatedAt', 'shikonaJp', 'currentRank'}
0_1000.json does not have consistent keys
- missing: {'createdAt', 'intai'}
0_1000.json does not have consistent keys
- missing: {'createdAt', 'updatedAt', 'shikonaJp', 'currentRank'}
0_1000.json does not have consistent keys
- missing: {'createdAt', 'intai'}
0_1000.json does not have consistent keys
- missing: {'createdAt', 'intai'}
0_1000.json does not have consistent keys
- missing: {'createdAt', 'updatedAt', 'shikonaJp', 'currentRank'}
0_1000.json does not have consistent keys
- missing: {'createdAt', 'intai'}
0_1000.json does not have consistent keys
- missing: {'createdAt', 'intai'}
0_1000.json does not have consistent keys
- missing: {'createdAt', 'intai'}
0_1000.json does not have consistent keys
- missing: {'createdAt', 'intai'}
0_1000.json does not have consistent keys
- missing: {'createdAt', 'intai'}
0_1000.json does not have consistent keys
- missing: {'createdAt', 'updatedAt', 'shikonaJp', 'currentRank'}
0_1000.json does not have consistent keys
- missing: {'createdAt', 'intai'}
0_1000.json does not have consistent keys
- missing: {'createdAt', 'intai'}
0_1000.json does not have consistent keys
- missing: {'createdAt', 'intai'}
0_1000.json does not have consistent keys
- missing: {'createdAt', 'updatedAt', 'shikonaJp', 'currentRank'}
0_1000.json does not have consistent keys
- missing: {'createdAt', 'intai'}
0_1000.json does not have consistent keys
- missing: {'createdAt', 'intai'}
0_1000.json does not have consistent keys
- missing: {'createdAt', 'intai'}
0_1000.json does not have consistent keys
- missing: {'createdAt', 'intai'}
0_1000.json does not have consistent keys
- missing: {'createdAt', 'intai'}
0_1000.json does not have consistent keys
- missing: {'createdAt', 'intai'}
0_1000.json does not have consistent keys
- missing: {'createdAt', 'intai'}
0_1000.json does not have consistent keys
- missing: {'createdAt', 'intai'}
0_1000.json does not have consistent keys
- missing: {'createdAt', 'intai'}
0_1000.json does not have consistent keys
- missing: {'createdAt', 'intai'}
0_1000.json does not have consistent keys
- missing: {'createdAt', 'updatedAt', 'shikonaJp', 'currentRank'}
0_1000.json does not have consistent keys
- missing: {'createdAt', 'intai'}
0_1000.json does not have consistent keys
- missing: {'createdAt', 'intai'}
0_1000.json does not have consistent keys
- missing: {'createdAt', 'intai'}
0_1000.json does not have consistent keys
- missing: {'createdAt', 'intai'}
0_1000.json does not have consistent keys
- missing: {'createdAt', 'intai'}
0_1000.json does not have consistent keys
- missing: {'createdAt', 'intai'}
0_1000.json does not have consistent keys
- missing: {'createdAt', 'intai'}
0_1000.json does not have consistent keys
- missing: {'createdAt', 'intai'}
0_1000.json does not have consistent keys
- missing: {'createdAt', 'updatedAt', 'shikonaJp', 'currentRank'}
0_1000.json does not have consistent keys
- missing: {'createdAt', 'intai'}
0_1000.json does not have consistent keys
- missing: {'createdAt', 'intai'}
0_1000.json does not have consistent keys
- missing: {'createdAt', 'intai'}
0_1000.json does not have consistent keys
- missing: {'createdAt', 'intai'}
0_1000.json does not have consistent keys
- missing: {'createdAt', 'intai'}
0_1000.json does not have consistent keys
- missing: {'createdAt', 'intai'}
0_1000.json does not have consistent keys
- missing: {'createdAt', 'intai'}
0_1000.json does not have consistent keys
- missing: {'createdAt', 'intai'}
0_1000.json does not have consistent keys
- missing: {'createdAt', 'intai'}
0_1000.json does not have consistent keys
- missing: {'createdAt', 'intai'}
0_1000.json does not have consistent keys
- missing: {'createdAt', 'intai'}
0_1000.json does not have consistent keys
- missing: {'createdAt', 'intai'}
0_1000.json does not have consistent keys
- missing: {'createdAt', 'updatedAt', 'shikonaJp', 'currentRank'}
0_1000.json does not have consistent keys
- missing: {'createdAt', 'intai'}
0_1000.json does not have consistent keys

shape: (9_051, 6)
┌──────┬─────────────────────┬────────────┬─────────────────────────────────┬────────┬────────────┐
│ id   ┆ shikonaEn           ┆ birthDate  ┆ shusshin                        ┆ debut  ┆ intai      │
│ ---  ┆ ---                 ┆ ---        ┆ ---                             ┆ ---    ┆ ---        │
│ i64  ┆ str                 ┆ date       ┆ str                             ┆ str    ┆ date       │
╞══════╪═════════════════════╪════════════╪═════════════════════════════════╪════════╪════════════╡
│ 1    ┆ Takakeisho Takanobu ┆ 1996-08-05 ┆ Hyogo-ken, Ashiya-shi           ┆ 201409 ┆ 2024-09-01 │
│ 2    ┆ Asanoyama           ┆ 1994-03-01 ┆ Toyama-ken, Toyama-shi          ┆ 201603 ┆ null       │
│ 3    ┆ Hakuoho             ┆ 2003-08-22 ┆ Tottori-ken, Kurayoshi-shi      ┆ 202301 ┆ null       │
│ 4    ┆ Kaizen              ┆ 1993-07-29 ┆ Kagoshima-ken, Oshima-gun, Tok… ┆ 201601 ┆ null       │
│ 5    ┆ Takerufuji          ┆ 1999-04-09 ┆ Aomori-ken, Goshogawara-shi     ┆ 202209 ┆ null       │
│ …    ┆ …                   ┆ …          ┆ …                               ┆ …      ┆ …          │
│ 9047 ┆ Uchiumi             ┆ 2003-04-17 ┆ Aichi                           ┆ 202503 ┆ null       │
│ 9048 ┆ Akenoyama           ┆ 2006-06-13 ┆ Mie                             ┆ 202503 ┆ null       │
│ 9049 ┆ Asakawasumi         ┆ 2008-04-09 ┆ Tokyo                           ┆ 202503 ┆ null       │
│ 9050 ┆ Fukuzaki            ┆ 2007-01-08 ┆ Kagoshima                       ┆ 202503 ┆ null       │
│ 9051 ┆ Goshima             ┆ 2003-02-26 ┆ Aichi                           ┆ 202503 ┆ null       │
└──────┴─────────────────────┴────────────┴─────────────────────────────────┴────────┴────────────┘

In [40]:
# PROCESS BASHO

base_dir_basho = "raw_data/basho"

all_item_keys_basho = set(
    [
        "id",
        "bashoId",
        "division",
        "day",
        "matchNo",
        "eastId",
        "eastShikona",
        "eastRank",
        "westId",
        "westShikona",
        "westRank",
        "kimarite",
        "winnerId",
        "winnerEn",
        "winnerJp",
    ]
)

all_data_basho: list[dict[str, Any]] = []
file_names_basho = os.listdir(base_dir_basho)
file_names_basho.sort()
for fn in file_names_basho:
    with open(os.path.join(base_dir_basho, fn)) as f:
        data = json.load(f)
        if "torikumi" in data:
            items = data["torikumi"]
            for item in items:
                keys = set(item.keys())
                if keys != all_item_keys_basho:
                    print(f"{fn} does not have consistent keys")
                    missing_keys = all_item_keys_basho.difference(keys)
                    if missing_keys:
                        print(f"missing keys: {missing_keys}")
                    extra_keys = keys.difference(all_item_keys_basho)
                    if extra_keys:
                        print(f"extra keys: {extra_keys}")
            all_data_basho += items
        else:
            print(f"{fn} does not contain 'torikumi' key.")


schema_basho: dict[str, pl.DataType] = {
    "id": pl.String,
    "bashoId": pl.String,
    "division": pl.String,
    "day": pl.UInt8,
    "matchNo": pl.UInt8,
    "eastId": pl.Int64,
    "eastRank": pl.String,
    "westId": pl.Int64,
    "westRank": pl.String,
    "kimarite": pl.String,
    "winnerId": pl.Int64,
}  # type: ignore

df_basho = pl.from_dicts(all_data_basho, schema=schema_basho)

year_month_from_id = pl.col("id").str.slice(0, 6).str.to_datetime("%Y%m")

# this is necessarily kinda approximate
# tournaments _usually_ start on the second Sunday of the month,
# but occasionally start on the first or third Sunday
df_basho = df_basho.insert_column(
    1,
    (
        year_month_from_id
        + pl.duration(days=14)
        - pl.duration(days=year_month_from_id.dt.weekday())
        + pl.duration(days=pl.col("day") - 1)
    )
    .dt.date()
    .alias("date"),
)

df_basho

195803_jonidan_01.json does not contain 'torikumi' key.
195803_jonidan_02.json does not contain 'torikumi' key.
195803_jonidan_03.json does not contain 'torikumi' key.
195803_jonidan_04.json does not contain 'torikumi' key.
195803_jonidan_05.json does not contain 'torikumi' key.
195803_jonidan_06.json does not contain 'torikumi' key.
195803_jonidan_07.json does not contain 'torikumi' key.
195803_jonidan_08.json does not contain 'torikumi' key.
195803_jonidan_09.json does not contain 'torikumi' key.
195803_jonidan_10.json does not contain 'torikumi' key.
195803_jonidan_11.json does not contain 'torikumi' key.
195803_jonidan_12.json does not contain 'torikumi' key.
195803_jonidan_13.json does not contain 'torikumi' key.
195803_jonidan_14.json does not contain 'torikumi' key.
195803_jonidan_15.json does not contain 'torikumi' key.
195803_jonokuchi_01.json does not contain 'torikumi' key.
195803_jonokuchi_02.json does not contain 'torikumi' key.
195803_jonokuchi_03.json does not contain 'torikumi' key.
195803_jonokuchi_04.json does not contain 'torikumi' key.
195803_jonokuchi_05.json does not contain 'torikumi' key.
195803_jonokuchi_06.json does not contain 'torikumi' key.
195803_jonokuchi_07.json does not contain 'torikumi' key.
195803_jonokuchi_08.json does not contain 'torikumi' key.
195803_jonokuchi_09.json does not contain 'torikumi' key.
195803_jonokuchi_10.json does not contain 'torikumi' key.
195803_jonokuchi_11.json does not contain 'torikumi' key.
195803_jonokuchi_12.json does not contain 'torikumi' key.
195803_jonokuchi_13.json does not contain 'torikumi' key.
195803_jonokuchi_14.json does not contain 'torikumi' key.
195803_jonokuchi_15.json does not contain 'torikumi' key.
195803_makushita_01.json does not contain 'torikumi' key.
195803_makushita_02.json does not contain 'torikumi' key.
195803_makushita_03.json does not contain 'torikumi' key.
195803_makushita_04.json does not contain 'torikumi' key.
195803_makushita_05.json does not contain 'torikumi' key.
195803_makushita_06.json does not contain 'torikumi' key.
195803_makushita_07.json does not contain 'torikumi' key.
195803_makushita_08.json does not contain 'torikumi' key.
195803_makushita_09.json does not contain 'torikumi' key.
195803_makushita_10.json does not contain 'torikumi' key.
195803_makushita_11.json does not contain 'torikumi' key.
195803_makushita_12.json does not contain 'torikumi' key.
195803_makushita_13.json does not contain 'torikumi' key.
195803_makushita_14.json does not contain 'torikumi' key.
195803_makushita_15.json does not contain 'torikumi' key.
195803_sandanme_01.json does not contain 'torikumi' key.
195803_sandanme_02.json does not contain 'torikumi' key.
195803_sandanme_03.json does not contain 'torikumi' key.
195803_sandanme_04.json does not contain 'torikumi' key.
195803_sandanme_05.json does not contain 'torikumi' key.
195803_sandanme_06.json does not contain 'torikumi' key.
195803_sandanme_07.json does not contain 'torikumi' key.
195803_sandanme_08.json does not contain 'torikumi' key.
195803_sandanme_09.json does not contain 'torikumi' key.
195803_sandanme_10.json does not contain 'torikumi' key.
195803_sandanme_11.json does not contain 'torikumi' key.
195803_sandanme_12.json does not contain 'torikumi' key.
195803_sandanme_13.json does not contain 'torikumi' key.
195803_sandanme_14.json does not contain 'torikumi' key.
195803_sandanme_15.json does not contain 'torikumi' key.
195805_jonidan_01.json does not contain 'torikumi' key.
195805_jonidan_02.json does not contain 'torikumi' key.
195805_jonidan_03.json does not contain 'torikumi' key.
195805_jonidan_04.json does not contain 'torikumi' key.
195805_jonidan_05.json does not contain 'torikumi' key.
195805_jonidan_06.json does not contain 'torikumi' key.
195805_jonidan_07.json does not contain 'torikumi' key.
195805_jonidan_08.json does not contain 'torikumi' key.
195805_jonidan_09.json does not contain 'torikumi' key.
195805_jonidan_10.json does not contain 'torikumi' key.
195805_jonidan_11.json does not contain 'torikumi' key.
195805_jonidan_12.json does not contain 'torikumi' key.
195805_jonidan_13.json does not contain 'torikumi' key.
195805_jonidan_14.json does not contain 'torikumi' key.
195805_jonidan_15.json does not contain 'torikumi' key.
195805_jonokuchi_01.json does not contain 'torikumi' key.
195805_jonokuchi_02.json does not contain 'torikumi' key.
195805_jonokuchi_03.json does not contain 'torikumi' key.
195805_jonokuchi_04.json does not contain 'torikumi' key.
195805_jonokuchi_05.json does not contain 'torikumi' key.
195805_jonokuchi_06.json does not contain 'torikumi' key.
195805_jonokuchi_07.json does not contain 'torikumi' key.
195805_jonokuchi_08.json does not contain 'torikumi' key.
195805_jonokuchi_09.json does not contain 'torikumi' key.
195805_jonokuchi_10.json does not contain 'torikumi' key.
195805_jonokuchi_11.json does not contain 'torikumi' key.
195805_jonokuchi_12.json does not contain 'torikumi' key.
195805_jonokuchi_13.json does not contain 'torikumi' key.
195805_jonokuchi_14.json does not contain 'torikumi' key.
195805_jonokuchi_15.json does not contain 'torikumi' key.
195805_makushita_01.json does not contain 'torikumi' key.
195805_makushita_02.json does not contain 'torikumi' key.
195805_makushita_03.json does not contain 'torikumi' key.
195805_makushita_04.json does not contain 'torikumi' key.
195805_makushita_05.json does not contain 'torikumi' key.
195805_makushita_06.json does not contain 'torikumi' key.
195805_makushita_07.json does not contain 'torikumi' key.
195805_makushita_08.json does not contain 'torikumi' key.
195805_makushita_09.json does not contain 'torikumi' key.
195805_makushita_10.json does not contain 'torikumi' key.
195805_makushita_11.json does not contain 'torikumi' key.
195805_makushita_12.json does not contain 'torikumi' key.
195805_makushita_13.json does not contain 'torikumi' key.
195805_makushita_14.json does not contain 'torikumi' key.
195805_makushita_15.json does not contain 'torikumi' key.
195805_sandanme_01.json does not contain 'torikumi' key.
195805_sandanme_02.json does not contain 'torikumi' key.
195805_sandanme_03.json does not contain 'torikumi' key.
195805_sandanme_04.json does not contain 'torikumi' key.
195805_sandanme_05.json does not contain 'torikumi' key.
195805_sandanme_06.json does not contain 'torikumi' key.
195805_sandanme_07.json does not contain 'torikumi' key.
195805_sandanme_08.json does not contain 'torikumi' key.
195805_sandanme_09.json does not contain 'torikumi' key.
195805_sandanme_10.json does not contain 'torikumi' key.
195805_sandanme_11.json does not contain 'torikumi' key.
195805_sandanme_12.json does not contain 'torikumi' key.
195805_sandanme_13.json does not contain 'torikumi' key.
195805_sandanme_14.json does not contain 'torikumi' key.
195805_sandanme_15.json does not contain 'torikumi' key.
195807_jonidan_01.json does not contain 'torikumi' key.
195807_jonidan_02.json does not contain 'torikumi' key.
195807_jonidan_03.json does not contain 'torikumi' key.
195807_jonidan_04.json does not contain 'torikumi' key.
195807_jonidan_05.json does not contain 'torikumi' key.
195807_jonidan_06.json does not contain 'torikumi' key.
195807_jonidan_07.json does not contain 'torikumi' key.
195807_jonidan_08.json does not contain 'torikumi' key.
195807_jonidan_09.json does not contain 'torikumi' key.
195807_jonidan_10.json does not contain 'torikumi' key.
195807_jonidan_11.json does not contain 'torikumi' key.
195807_jonidan_12.json does not contain 'torikumi' key.
195807_jonidan_13.json does not contain 'torikumi' key.
195807_jonidan_14.json does not contain 'torikumi' key.
195807_jonidan_15.json does not contain 'torikumi' key.
195807_jonokuchi_01.json does not contain 'torikumi' key.
195807_jonokuchi_02.json does not contain 'torikumi' key.
195807_jonokuchi_03.json does not contain 'torikumi' key.
195807_jonokuchi_04.json does not contain 'torikumi' key.
195807_jonokuchi_05.json does not contain 'torikumi' key.
195807_jonokuchi_06.json does not contain 'torikumi' key.
195807_jonokuchi_07.json does not contain 'torikumi' key.
195807_jonokuchi_08.json does not contain 'torikumi' key.
195807_jonokuchi_09.json does not contain 'torikumi' key.
195807_jonokuchi_10.json does not contain 'torikumi' key.
195807_jonokuchi_11.json does not contain 'torikumi' key.
195807_jonokuchi_12.json does not contain 'torikumi' key.
195807_jonokuchi_13.json does not contain 'torikumi' key.
195807_jonokuchi_14.json does not contain 'torikumi' key.
195807_jonokuchi_15.json does not contain 'torikumi' key.
195807_makushita_01.json does not contain 'torikumi' key.
195807_makushita_02.json does not contain 'torikumi' key.
195807_makushita_03.json does not contain 'torikumi' key.
195807_makushita_04.json does not contain 'torikumi' key.
195807_makushita_05.json does not contain 'torikumi' key.
195807_makushita_06.json does not contain 'torikumi' key.
195807_makushita_07.json does not contain 'torikumi' key.
195807_makushita_08.json does not contain 'torikumi' key.
195807_makushita_09.json does not contain 'torikumi' key.
195807_makushita_10.json does not contain 'torikumi' key.
195807_makushita_11.json does not contain 'torikumi' key.
195807_makushita_12.json does not contain 'torikumi' key.
195807_makushita_13.json does not contain 'torikumi' key.
195807_makushita_14.json does not contain 'torikumi' key.
195807_makushita_15.json does not contain 'torikumi' key.
195807_sandanme_01.json does not contain 'torikumi' key.
195807_sandanme_02.json does not contain 'torikumi' key.
195807_sandanme_03.json does not contain 'torikumi' key.
195807_sandanme_04.json does not contain 'torikumi' key.
195807_sandanme_05.json does not contain 'torikumi' key.
195807_sandanme_06.json does not contain 'torikumi' key.
195807_sandanme_07.json does not contain 'torikumi' key.
195807_sandanme_08.json does not contain 'torikumi' key.
195807_sandanme_09.json does not contain 'torikumi' key.
195807_sandanme_10.json does not contain 'torikumi' key.
195807_sandanme_11.json does not contain 'torikumi' key.
195807_sandanme_12.json does not contain 'torikumi' key.
195807_sandanme_13.json does not contain 'torikumi' key.
195807_sandanme_14.json does not contain 'torikumi' key.
195807_sandanme_15.json does not contain 'torikumi' key.
195809_jonidan_01.json does not contain 'torikumi' key.
195809_jonidan_02.json does not contain 'torikumi' key.
195809_jonidan_03.json does not contain 'torikumi' key.
195809_jonidan_04.json does not contain 'torikumi' key.
195809_jonidan_05.json does not contain 'torikumi' key.
195809_jonidan_06.json does not contain 'torikumi' key.
195809_jonidan_07.json does not contain 'torikumi' key.
195809_jonidan_08.json does not contain 'torikumi' key.
195809_jonidan_09.json does not contain 'torikumi' key.
195809_jonidan_10.json does not contain 'torikumi' key.
195809_jonidan_11.json does not contain 'torikumi' key.
195809_jonidan_12.json does not contain 'torikumi' key.
195809_jonidan_13.json does not contain 'torikumi' key.
195809_jonidan_14.json does not contain 'torikumi' key.
195809_jonidan_15.json does not contain 'torikumi' key.
195809_jonokuchi_01.json does not contain 'torikumi' key.
195809_jonokuchi_02.json does not contain 'torikumi' key.
195809_jonokuchi_03.json does not contain 'torikumi' key.
195809_jonokuchi_04.json does not contain 'torikumi' key.
195809_jonokuchi_05.json does not contain 'torikumi' key.
195809_jonokuchi_06.json does not contain 'torikumi' key.
195809_jonokuchi_07.json does not contain 'torikumi' key.
195809_jonokuchi_08.json does not contain 'torikumi' key.
195809_jonokuchi_09.json does not contain 'torikumi' key.
195809_jonokuchi_10.json does not contain 'torikumi' key.
195809_jonokuchi_11.json does not contain 'torikumi' key.
195809_jonokuchi_12.json does not contain 'torikumi' key.
195809_jonokuchi_13.json does not contain 'torikumi' key.
195809_jonokuchi_14.json does not contain 'torikumi' key.
195809_jonokuchi_15.json does not contain 'torikumi' key.
195809_makushita_01.json does not contain 'torikumi' key.
195809_makushita_02.json does not contain 'torikumi' key.
195809_makushita_03.json does not contain 'torikumi' key.
195809_makushita_04.json does not contain 'torikumi' key.
195809_makushita_05.json does not contain 'torikumi' key.
195809_makushita_06.json does not contain 'torikumi' key.
195809_makushita_07.json does not contain 'torikumi' key.
195809_makushita_08.json does not contain 'torikumi' key.
195809_makushita_09.json does not contain 'torikumi' key.
195809_makushita_10.json does not contain 'torikumi' key.
195809_makushita_11.json does not contain 'torikumi' key.
195809_makushita_12.json does not contain 'torikumi' key.
195809_makushita_13.json does not contain 'torikumi' key.
195809_makushita_14.json does not contain 'torikumi' key.
195809_makushita_15.json does not contain 'torikumi' key.
195809_sandanme_01.json does not contain 'torikumi' key.
195809_sandanme_02.json does not contain 'torikumi' key.
195809_sandanme_03.json does not contain 'torikumi' key.
195809_sandanme_04.json does not contain 'torikumi' key.
195809_sandanme_05.json does not contain 'torikumi' key.
195809_sandanme_06.json does not contain 'torikumi' key.
195809_sandanme_07.json does not contain 'torikumi' key.
195809_sandanme_08.json does not contain 'torikumi' key.
195809_sandanme_09.json does not contain 'torikumi' key.
195809_sandanme_10.json does not contain 'torikumi' key.
195809_sandanme_11.json does not contain 'torikumi' key.
195809_sandanme_12.json does not contain 'torikumi' key.
195809_sandanme_13.json does not contain 'torikumi' key.
195809_sandanme_14.json does not contain 'torikumi' key.
195809_sandanme_15.json does not contain 'torikumi' key.
195811_jonidan_01.json does not contain 'torikumi' key.
195811_jonidan_02.json does not contain 'torikumi' key.
195811_jonidan_03.json does not contain 'torikumi' key.
195811_jonidan_04.json does not contain 'torikumi' key.
195811_jonidan_05.json does not contain 'torikumi' key.
195811_jonidan_06.json does not contain 'torikumi' key.
195811_jonidan_07.json does not contain 'torikumi' key.
195811_jonidan_08.json does not contain 'torikumi' key.
195811_jonidan_09.json does not contain 'torikumi' key.
195811_jonidan_10.json does not contain 'torikumi' key.
195811_jonidan_11.json does not contain 'torikumi' key.
195811_jonidan_12.json does not contain 'torikumi' key.
195811_jonidan_13.json does not contain 'torikumi' key.
195811_jonidan_14.json does not contain 'torikumi' key.
195811_jonidan_15.json does not contain 'torikumi' key.
195811_jonokuchi_01.json does not contain 'torikumi' key.
195811_jonokuchi_02.json does not contain 'torikumi' key.
195811_jonokuchi_03.json does not contain 'torikumi' key.
195811_jonokuchi_04.json does not contain 'torikumi' key.
195811_jonokuchi_05.json does not contain 'torikumi' key.
195811_jonokuchi_06.json does not contain 'torikumi' key.
195811_jonokuchi_07.json does not contain 'torikumi' key.
195811_jonokuchi_08.json does not contain 'torikumi' key.
195811_jonokuchi_09.json does not contain 'torikumi' key.
195811_jonokuchi_10.json does not contain 'torikumi' key.
195811_jonokuchi_11.json does not contain 'torikumi' key.
195811_jonokuchi_12.json does not contain 'torikumi' key.
195811_jonokuchi_13.json does not contain 'torikumi' key.
195811_jonokuchi_14.json does not contain 'torikumi' key.
195811_jonokuchi_15.json does not contain 'torikumi' key.
195811_makushita_01.json does not contain 'torikumi' key.
195811_makushita_02.json does not contain 'torikumi' key.
195811_makushita_03.json does not contain 'torikumi' key.
195811_makushita_04.json does not contain 'torikumi' key.
195811_makushita_05.json does not contain 'torikumi' key.
195811_makushita_06.json does not contain 'torikumi' key.
195811_makushita_07.json does not contain 'torikumi' key.
195811_makushita_08.json does not contain 'torikumi' key.
195811_makushita_09.json does not contain 'torikumi' key.
195811_makushita_10.json does not contain 'torikumi' key.
195811_makushita_11.json does not contain 'torikumi' key.
195811_makushita_12.json does not contain 'torikumi' key.
195811_makushita_13.json does not contain 'torikumi' key.
195811_makushita_14.json does not contain 'torikumi' key.
195811_makushita_15.json does not contain 'torikumi' key.
195811_sandanme_01.json does not contain 'torikumi' key.
195811_sandanme_02.json does not contain 'torikumi' key.
195811_sandanme_03.json does not contain 'torikumi' key.
195811_sandanme_04.json does not contain 'torikumi' key.
195811_sandanme_05.json does not contain 'torikumi' key.
195811_sandanme_06.json does not contain 'torikumi' key.
195811_sandanme_07.json does not contain 'torikumi' key.
195811_sandanme_08.json does not contain 'torikumi' key.
195811_sandanme_09.json does not contain 'torikumi' key.
195811_sandanme_10.json does not contain 'torikumi' key.
195811_sandanme_11.json does not contain 'torikumi' key.
195811_sandanme_12.json does not contain 'torikumi' key.
195811_sandanme_13.json does not contain 'torikumi' key.
195811_sandanme_14.json does not contain 'torikumi' key.
195811_sandanme_15.json does not contain 'torikumi' key.
195901_jonidan_01.json does not contain 'torikumi' key.
195901_jonidan_02.json does not contain 'torikumi' key.
195901_jonidan_03.json does not contain 'torikumi' key.
195901_jonidan_04.json does not contain 'torikumi' key.
195901_jonidan_05.json does not contain 'torikumi' key.
195901_jonidan_06.json does not contain 'torikumi' key.
195901_jonidan_07.json does not contain 'torikumi' key.
195901_jonidan_08.json does not contain 'torikumi' key.
195901_jonidan_09.json does not contain 'torikumi' key.
195901_jonidan_10.json does not contain 'torikumi' key.
195901_jonidan_11.json does not contain 'torikumi' key.
195901_jonidan_12.json does not contain 'torikumi' key.
195901_jonidan_13.json does not contain 'torikumi' key.
195901_jonidan_14.json does not contain 'torikumi' key.
195901_jonidan_15.json does not contain 'torikumi' key.
195901_jonokuchi_01.json does not contain 'torikumi' key.
195901_jonokuchi_02.json does not contain 'torikumi' key.
195901_jonokuchi_03.json does not contain 'torikumi' key.
195901_jonokuchi_04.json does not contain 'torikumi' key.
195901_jonokuchi_05.json does not contain 'torikumi' key.
195901_jonokuchi_06.json does not contain 'torikumi' key.
195901_jonokuchi_07.json does not contain 'torikumi' key.
195901_jonokuchi_08.json does not contain 'torikumi' key.
195901_jonokuchi_09.json does not contain 'torikumi' key.
195901_jonokuchi_10.json does not contain 'torikumi' key.
195901_jonokuchi_11.json does not contain 'torikumi' key.
195901_jonokuchi_12.json does not contain 'torikumi' key.
195901_jonokuchi_13.json does not contain 'torikumi' key.
195901_jonokuchi_14.json does not contain 'torikumi' key.
195901_jonokuchi_15.json does not contain 'torikumi' key.
195901_makushita_01.json does not contain 'torikumi' key.
195901_makushita_02.json does not contain 'torikumi' key.
195901_makushita_03.json does not contain 'torikumi' key.
195901_makushita_04.json does not contain 'torikumi' key.
195901_makushita_05.json does not contain 'torikumi' key.
195901_makushita_06.json does not contain 'torikumi' key.
195901_makushita_07.json does not contain 'torikumi' key.
195901_makushita_08.json does not contain 'torikumi' key.
195901_makushita_09.json does not contain 'torikumi' key.
195901_makushita_10.json does not contain 'torikumi' key.
195901_makushita_11.json does not contain 'torikumi' key.
195901_makushita_12.json does not contain 'torikumi' key.
195901_makushita_13.json does not contain 'torikumi' key.
195901_makushita_14.json does not contain 'torikumi' key.
195901_makushita_15.json does not contain 'torikumi' key.
195901_sandanme_01.json does not contain 'torikumi' key.
195901_sandanme_02.json does not contain 'torikumi' key.
195901_sandanme_03.json does not contain 'torikumi' key.
195901_sandanme_04.json does not contain 'torikumi' key.

shape: (729_955, 12)
┌─────────────┬────────────┬─────────┬──────────┬───┬────────┬─────────────┬────────────┬──────────┐
│ id          ┆ date       ┆ bashoId ┆ division ┆ … ┆ westId ┆ westRank    ┆ kimarite   ┆ winnerId │
│ ---         ┆ ---        ┆ ---     ┆ ---      ┆   ┆ ---    ┆ ---         ┆ ---        ┆ ---      │
│ str         ┆ date       ┆ str     ┆ str      ┆   ┆ i64    ┆ str         ┆ str        ┆ i64      │
╞═════════════╪════════════╪═════════╪══════════╪═══╪════════╪═════════════╪════════════╪══════════╡
│ 195803-1-13 ┆ 1958-03-09 ┆ 195803  ┆ Juryo    ┆ … ┆ 1325   ┆ Juryo 24    ┆ uchigake   ┆ 1311     │
│ 11-1325     ┆            ┆         ┆          ┆   ┆        ┆ West        ┆            ┆          │
│ 195803-1-13 ┆ 1958-03-09 ┆ 195803  ┆ Juryo    ┆ … ┆ 1306   ┆ Juryo 24    ┆ yorikiri   ┆ 1320     │
│ 20-1306     ┆            ┆         ┆          ┆   ┆        ┆ East        ┆            ┆          │
│ 195803-1-13 ┆ 1958-03-09 ┆ 195803  ┆ Juryo    ┆ … ┆ 1309   ┆ Juryo 22    ┆ kotenage   ┆ 1309     │
│ 13-1309     ┆            ┆         ┆          ┆   ┆        ┆ West        ┆            ┆          │
│ 195803-1-13 ┆ 1958-03-09 ┆ 195803  ┆ Juryo    ┆ … ┆ 1326   ┆ Juryo 21    ┆ tsuridashi ┆ 1319     │
│ 19-1326     ┆            ┆         ┆          ┆   ┆        ┆ West        ┆            ┆          │
│ 195803-1-13 ┆ 1958-03-09 ┆ 195803  ┆ Juryo    ┆ … ┆ 1315   ┆ Juryo 20    ┆ makiotoshi ┆ 1315     │
│ 10-1315     ┆            ┆         ┆          ┆   ┆        ┆ West        ┆            ┆          │
│ …           ┆ …          ┆ …       ┆ …        ┆ … ┆ …      ┆ …           ┆ …          ┆ …        │
│ 202503-15-1 ┆ 2025-03-23 ┆ 202503  ┆ Sandanme ┆ … ┆ 215    ┆ Sandanme 15 ┆ yoritaoshi ┆ 184      │
│ 9-184-215   ┆            ┆         ┆          ┆   ┆        ┆ East        ┆            ┆          │
│ 202503-15-2 ┆ 2025-03-23 ┆ 202503  ┆ Sandanme ┆ … ┆ 153    ┆ Sandanme 11 ┆ yorikiri   ┆ 153      │
│ 0-160-153   ┆            ┆         ┆          ┆   ┆        ┆ West        ┆            ┆          │
│ 202503-15-2 ┆ 2025-03-23 ┆ 202503  ┆ Sandanme ┆ … ┆ 119    ┆ Sandanme 9  ┆ yoritaoshi ┆ 119      │
│ 1-500-119   ┆            ┆         ┆          ┆   ┆        ┆ West        ┆            ┆          │
│ 202503-15-2 ┆ 2025-03-23 ┆ 202503  ┆ Sandanme ┆ … ┆ 286    ┆ Sandanme 8  ┆ shitatenag ┆ 8852     │
│ 2-8852-286  ┆            ┆         ┆          ┆   ┆        ┆ West        ┆ e          ┆          │
│ 202503-15-3 ┆ 2025-03-23 ┆ 202503  ┆ Sandanme ┆ … ┆ 576    ┆ Sandanme 69 ┆ yorikiri   ┆ 335      │
│ -335-576    ┆            ┆         ┆          ┆   ┆        ┆ West        ┆            ┆          │
└─────────────┴────────────┴─────────┴──────────┴───┴────────┴─────────────┴────────────┴──────────┘

In [41]:
df_rikishi_east = df_rikishi.clone().rename(
    {
        "shikonaEn": "shikonaEn_east",
        "birthDate": "birthDate_east",
        "shusshin": "shusshin_east",
        "debut": "debut_east",
        "intai": "intai_east",
    }
)
df_rikishi_west = df_rikishi.clone().rename(
    {
        "shikonaEn": "shikonaEn_west",
        "birthDate": "birthDate_west",
        "shusshin": "shusshin_west",
        "debut": "debut_west",
        "intai": "intai_west",
    }
)


df = df_basho
df = df.join(df_rikishi_east, left_on="eastId", right_on="id", how="left")
df = df.join(df_rikishi_west, left_on="westId", right_on="id", how="left")

df.write_parquet("processed_data/torikumi.parquet")

df

shape: (729_955, 22)
┌────────────┬────────────┬─────────┬──────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ id         ┆ date       ┆ bashoId ┆ division ┆ … ┆ birthDate ┆ shusshin_ ┆ debut_wes ┆ intai_wes │
│ ---        ┆ ---        ┆ ---     ┆ ---      ┆   ┆ _west     ┆ west      ┆ t         ┆ t         │
│ str        ┆ date       ┆ str     ┆ str      ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---       │
│            ┆            ┆         ┆          ┆   ┆ date      ┆ str       ┆ str       ┆ date      │
╞════════════╪════════════╪═════════╪══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 195803-1-1 ┆ 1958-03-09 ┆ 195803  ┆ Juryo    ┆ … ┆ 1937-03-1 ┆ Yamanashi ┆ 195303    ┆ 1968-11-0 │
│ 311-1325   ┆            ┆         ┆          ┆   ┆ 8         ┆ -ken,     ┆           ┆ 1         │
│            ┆            ┆         ┆          ┆   ┆           ┆ Kofu-shi  ┆           ┆           │
│ 195803-1-1 ┆ 1958-03-09 ┆ 195803  ┆ Juryo    ┆ … ┆ 1935-01-0 ┆ Hokkaido, ┆ 195205    ┆ 1958-09-0 │
│ 320-1306   ┆            ┆         ┆          ┆   ┆ 2         ┆ Mikasa-sh ┆           ┆ 1         │
│            ┆            ┆         ┆          ┆   ┆           ┆ i         ┆           ┆           │
│ 195803-1-1 ┆ 1958-03-09 ┆ 195803  ┆ Juryo    ┆ … ┆ 1935-05-2 ┆ Toyama-ke ┆ 195105    ┆ 1960-03-0 │
│ 313-1309   ┆            ┆         ┆          ┆   ┆ 1         ┆ n,        ┆           ┆ 1         │
│            ┆            ┆         ┆          ┆   ┆           ┆ Himi-shi  ┆           ┆           │
│ 195803-1-1 ┆ 1958-03-09 ┆ 195803  ┆ Juryo    ┆ … ┆ 1934-07-2 ┆ Aomori-ke ┆ 195109    ┆ 1959-05-0 │
│ 319-1326   ┆            ┆         ┆          ┆   ┆ 7         ┆ n, Minami ┆           ┆ 1         │
│            ┆            ┆         ┆          ┆   ┆           ┆ tsugaru-g ┆           ┆           │
│            ┆            ┆         ┆          ┆   ┆           ┆ un        ┆           ┆           │
│ 195803-1-1 ┆ 1958-03-09 ┆ 195803  ┆ Juryo    ┆ … ┆ 1931-07-1 ┆ Nagasaki- ┆ 194905    ┆ 1965-01-0 │
│ 310-1315   ┆            ┆         ┆          ┆   ┆ 8         ┆ ken, Isah ┆           ┆ 1         │
│            ┆            ┆         ┆          ┆   ┆           ┆ aya-shi   ┆           ┆           │
│ …          ┆ …          ┆ …       ┆ …        ┆ … ┆ …         ┆ …         ┆ …         ┆ …         │
│ 202503-15- ┆ 2025-03-23 ┆ 202503  ┆ Sandanme ┆ … ┆ 2003-08-0 ┆ Fukushima ┆ 201903    ┆ null      │
│ 19-184-215 ┆            ┆         ┆          ┆   ┆ 4         ┆ -ken, Kor ┆           ┆           │
│            ┆            ┆         ┆          ┆   ┆           ┆ iyama-shi ┆           ┆           │
│ 202503-15- ┆ 2025-03-23 ┆ 202503  ┆ Sandanme ┆ … ┆ 1986-07-1 ┆ Tokyo-to, ┆ 200303    ┆ null      │
│ 20-160-153 ┆            ┆         ┆          ┆   ┆ 7         ┆ Katsushik ┆           ┆           │
│            ┆            ┆         ┆          ┆   ┆           ┆ a-ku      ┆           ┆           │
│ 202503-15- ┆ 2025-03-23 ┆ 202503  ┆ Sandanme ┆ … ┆ 1999-08-0 ┆ Aichi-ken ┆ 201503    ┆ null      │
│ 21-500-119 ┆            ┆         ┆          ┆   ┆ 2         ┆ ,         ┆           ┆           │
│            ┆            ┆         ┆          ┆   ┆           ┆ Konan-shi ┆           ┆           │
│ 202503-15- ┆ 2025-03-23 ┆ 202503  ┆ Sandanme ┆ … ┆ 2000-07-2 ┆ Hyogo-ken ┆ 201903    ┆ null      │
│ 22-8852-28 ┆            ┆         ┆          ┆   ┆ 9         ┆ , Himeji- ┆           ┆           │
│ 6          ┆            ┆         ┆          ┆   ┆           ┆ shi       ┆           ┆           │
│ 202503-15- ┆ 2025-03-23 ┆ 202503  ┆ Sandanme ┆ … ┆ 1998-07-1 ┆ Gifu-ken, ┆ 201405    ┆ null      │
│ 3-335-576  ┆            ┆         ┆          ┆   ┆ 1         ┆ Kakamigah ┆           ┆           │
│            ┆            ┆         ┆          ┆   ┆           ┆ ara-shi   ┆           ┆           │
└────────────┴────────────┴─────────┴──────────┴───┴───────────┴───────────┴───────────┴───────────┘